/*
 * Ultrasonic.h
 *
 *  Created on: Jun 25, 2025
 *      Author: SIGMA
 */

#ifndef HAL_ULTRASONIC_H_
#define HAL_ULTRASONIC_H_
#include"../Common/std_types.h"
#include"../MCAL/gpio.h"
#include"../MCAL/icu.h"
#include<util/delay.h>


//SELECT THE TRIGGER PIN
#define Ultrasonic_Trigger_PORT_ID  PORTD_ID
#define Ultrasonic_Trigger_PIN_ID   PIN7_ID


// =============  THE FUNCTIONS  ============= //

void Ultrasonic_init(void);
/* ▪ Description:
▪ Initialize the ICU driver as required.
▪ Set up the ICU callback function.
▪ Set the direction for the trigger pin as output through
the GPIO driver.
▪ Inputs: None.
▪ Return: None. */

void Ultrasonic_Trigger(void);
/* ▪ Description:
▪ Send the trigger pulse to the ultrasonic sensor.
▪ Inputs: None.
▪ Return: None. */



uint16 Ultrasonic_readDistance(void);
/*▪ Description:
▪ Send the trigger pulse by using the Ultrasonic_Trigger
function.
▪ Start the measurement process via the ICU driver.
6
▪ Inputs: None.
▪ Return: The measured distance in centimeters.*/

void Ultrasonic_edgeProcessing(void);

	/* Description:
	▪ This is the callback function called by the ICU driver.
	▪ It calculates the high time (pulse time) generated by
	the ultrasonic sensor.
	▪ Inputs: None.
	▪ Return: None. */








#endif /* HAL_ULTRASONIC_H_ */
